apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # or LoadBalancer if on cloud (like EKS/GKE)
  selector:
    app: frontend
  ports:
    - port: 80         # Exposed inside cluster
      targetPort: 80   # Container port
      nodePort: 30080  # Exposed outside (localhost:30080)
