version: "3.9"

services:
  auth4:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth4:1.0
    ports:
      - "8082:5000"
    restart: always
    networks:
      - authnet4

networks:
  authnet4: