version: "3.9"

services:
  order4:
    build:
      context: .
      dockerfile: Dockerfile
    image: order4:1.0
    ports:
      - "8083:5001"
    restart: always
    networks:
      - ordernet4

networks:
  ordernet4:
